POST http://localhost:3000/produtos
Content-Type: application/json

{
    "produto": "Peixe",
    "preco": 35,
    "quantidade" : 2
}

###

GET http://localhost:3000/produtos
Content-Type: application/json

###

PUT http://localhost:3000/produto-venda/2
Content-Type: application/json

###

PUT http://localhost:3000/produto-compra/2
Content-Type: application/json

###

PUT http://localhost:3000/produto-venda/1/3
Content-Type: application/json

###

PUT http://localhost:3000/produto-compra/1/5
Content-Type: application/json

###

DELETE http://localhost:3000/produtos/3

###

PUT http://localhost:3000/produtos/2
Content-Type: application/json

{
    "produto": "Peixe",
    "preco": 30,
    "quantidade" : 5
}

###

GET http://localhost:3000/produtos/2
Content-Type: application/json